%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('ArrayOfCenaZlota',{anyAttribs,'gold_store'}).
-record('gold_store', {anyAttribs, 'gold_type'}).
-record('gold_type', {anyAttribs, 'date', 'price'}).

-record('ExchangeRatesSeries',{anyAttribs,'table','currency_name','currency_code','ExchangeRatesSeries/Rates'}).
-record('ExchangeRatesSeries/Rates',{anyAttribs,'currency_value'}).
-record('currency_value',{anyAttribs,'something','date','value'}).