%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-ifndef(ERLSOM_ANY_ATTRIB_TYPES).
-define(ERLSOM_ANY_ATTRIB_TYPES, true).
-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.
-endif.

-ifndef(ERLSOM_QNAME_TYPES).
-define(ERLSOM_QNAME_TYPES, true).
%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).
-endif.



-record(currency_value, {anyAttribs :: anyAttribs(),
	'No' :: string(),
	'EffectiveDate' :: string(),
	'Mid' :: string()}).

-type currency_value() :: #currency_value{}.


-record('ExchangeRatesSeries', {anyAttribs :: anyAttribs(),
	'Table' :: string(),
	'Currency' :: string(),
	'Code' :: string(),
	'Rates' :: 'ExchangeRatesSeries/Rates'()}).

-type 'ExchangeRatesSeries'() :: #'ExchangeRatesSeries'{}.


-record('ExchangeRatesSeries/Rates', {anyAttribs :: anyAttribs(),
	'Rate' :: [currency_value()]}).

-type 'ExchangeRatesSeries/Rates'() :: #'ExchangeRatesSeries/Rates'{}.